name: Deploy to GH Pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: run npm install and generate static files
      run: |
        npm install
        npm run generate
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      run: echo "Skipping tests"